apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: gh-wh-demo
  namespace: gh-wh-demo
spec:
  webhookReceivers: 
    - name: gh-wh-receiver
      github:
        secretRef:
          name: gh-wh-secret
