apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: dh-wh-demo
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: dh-wh-demo
  namespace: dh-wh-demo
spec:
  webhookReceivers:
    - name: dh-wh-receiver
      dockerhub:
        secretRef:
          name: dh-wh-secret
