apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: my-dh-warehouse
  namespace: kargo-demo
spec:
  # Set high interval for webhook-driven refreshes
  interval: 30m
  subscriptions:
  - image:
      repoURL: docker.io/fykaa/kargo-demo
      imageSelectionStrategy: SemVer
      strictSemvers: false